/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import static Proyecto.Login.ArrayUsuarios;
import static Proyecto.Login.rol;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miche
 */
public class Reportes extends javax.swing.JFrame {
    
    private DefaultTableModel modelo;
    int contador = 0;

    private int yMouse;
    private int xMouse;

    /**
     * Creates new form Reportes
     */
    
    DefaultTableModel Tabla;
    public static ArrayList<Usuarios> ArrayUsuarios;
    
    public Reportes() throws IOException {
        initComponents();
        Cargar();
        CargarDatos();
        ArrayUsuarios = new ArrayList<Usuarios>();
        Tabla = (DefaultTableModel) Tabla_de_Reportes.getModel();
    }
    
    public void Motrar_Tabla() {
        
        modelo = new DefaultTableModel();
        Tabla_de_Reportes.setModel(modelo);      
    }
    
    public void Cargar() {

        String datos[][] = {};
        String columna[] = {"Nombre", "Apellidos", "Correo", "Usuario", "Perfil"};

        modelo = new DefaultTableModel(datos, columna);
        Tabla_de_Reportes.setModel(modelo);

    }

    public void CargarDatos() {

        Usuarios U = new Usuarios();

        for (int i = 0; i < Login.ArrayUsuarios.size(); i++) {
            U = (Usuarios) Login.ArrayUsuarios.get(i);
            modelo.insertRow(contador, new Object[]{});
            modelo.setValueAt(U.getNombre(), contador, 0);
            modelo.setValueAt(U.getApellido(), contador, 1);
            modelo.setValueAt(U.getCorreo(), contador, 2);
            modelo.setValueAt(U.getUsuario(), contador, 3);
            modelo.setValueAt(U.getRol(), contador, 4);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Panel_Reportes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Reporte_FastChat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Nombre_Documento = new javax.swing.JTextField();
        Panel_Reporte_Usuarios = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_de_Reportes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Panel_Exit_Reportes = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondodegradado_1.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondodegradado_1.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondodegradado_1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Reportes");
        Panel_Reportes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setText("Nombre del documento");
        Panel_Reportes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        Panel_Reporte_FastChat.setBackground(new java.awt.Color(91, 155, 213));
        Panel_Reporte_FastChat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Reporte_FastChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Reporte_FastChatMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Generar reporte - Acerca de FastChat");

        javax.swing.GroupLayout Panel_Reporte_FastChatLayout = new javax.swing.GroupLayout(Panel_Reporte_FastChat);
        Panel_Reporte_FastChat.setLayout(Panel_Reporte_FastChatLayout);
        Panel_Reporte_FastChatLayout.setHorizontalGroup(
            Panel_Reporte_FastChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Reporte_FastChatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Reporte_FastChatLayout.setVerticalGroup(
            Panel_Reporte_FastChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Reporte_FastChatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        Panel_Reportes.add(Panel_Reporte_FastChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 270, -1));
        Panel_Reportes.add(Txt_Nombre_Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 254, 27));

        Panel_Reporte_Usuarios.setBackground(new java.awt.Color(91, 155, 213));
        Panel_Reporte_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Reporte_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Reporte_UsuariosMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Generar reporte usuarios");

        javax.swing.GroupLayout Panel_Reporte_UsuariosLayout = new javax.swing.GroupLayout(Panel_Reporte_Usuarios);
        Panel_Reporte_Usuarios.setLayout(Panel_Reporte_UsuariosLayout);
        Panel_Reporte_UsuariosLayout.setHorizontalGroup(
            Panel_Reporte_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Reporte_UsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Reporte_UsuariosLayout.setVerticalGroup(
            Panel_Reporte_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Reporte_UsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Reportes.add(Panel_Reporte_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        Tabla_de_Reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Correo", "Usuario", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_de_Reportes);

        Panel_Reportes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 690, 250));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Atrás");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel_Reportes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel_Exit_ReportesLayout = new javax.swing.GroupLayout(Panel_Exit_Reportes);
        Panel_Exit_Reportes.setLayout(Panel_Exit_ReportesLayout);
        Panel_Exit_ReportesLayout.setHorizontalGroup(
            Panel_Exit_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Exit_ReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Exit_ReportesLayout.setVerticalGroup(
            Panel_Exit_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Exit_ReportesLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        Panel_Reportes.add(Panel_Exit_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondodegradado_1.png"))); // NOI18N
        Panel_Reportes.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel_Reporte_FastChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Reporte_FastChatMouseClicked

        Diseño_De_Reportes Reporte_FastChat = new Diseño_De_Reportes(Txt_Nombre_Documento.getText(), new Date().toString(), "C:\\Users\\Miche\\Documents\\NetBeansProjects\\FastChat\\Sistema de Mensajería - FastChat\\Sistema de Mensajería - Prueba (1)\\Cambios\\Sistema de Mensajería - Prueba\\src\\Imágenes\\Logo.png");
        Reporte_FastChat.Generar_Reporte_FastChat();

    }//GEN-LAST:event_Panel_Reporte_FastChatMouseClicked

    private void Panel_Reporte_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Reporte_UsuariosMouseClicked

        Diseño_De_Reportes Reporte_Usuarios = new Diseño_De_Reportes(Txt_Nombre_Documento.getText(), new Date().toString(), "C:\\Users\\Miche\\Desktop\\Universidad\\2021\\Programación 1\\Proyecto\\Primer avance del proyecto\\Grupo.png", Login.ArrayUsuarios);
        Reporte_Usuarios.Generar_Reporte_Usuarios();

    }//GEN-LAST:event_Panel_Reporte_UsuariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Contactos C = new Contactos();
        C.setVisible(true);
        this.dispose();
        new Contactos(Ingreso.TxtUsuario.getText()).setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered

        Panel_Exit_Reportes.setBackground(Color.red);

    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel13MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Reportes().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Reportes.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Exit_Reportes;
    private javax.swing.JPanel Panel_Reporte_FastChat;
    private javax.swing.JPanel Panel_Reporte_Usuarios;
    private javax.swing.JPanel Panel_Reportes;
    private javax.swing.JTable Tabla_de_Reportes;
    private javax.swing.JTextField Txt_Nombre_Documento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
