/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import static Proyecto.Login.ArrayUsuarios;
import static Proyecto.Login.rol;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miche
 */
public class Reportes extends javax.swing.JFrame {
    
    private int yMouse;
    private int xMouse;

    /**
     * Creates new form Reportes
     */

    ArrayList<Usuarios> ArrayUsuarios;
    DefaultTableModel Tabla;
    
    public Reportes() {
        initComponents();
        ArrayUsuarios = new ArrayList<Usuarios>();
        Tabla = (DefaultTableModel) Tabla_de_Reportes.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Panel_Reportes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panel_Reporte_Usuarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Txt_Nombre_Documento = new javax.swing.JTextField();
        Panel_Reporte_Perfiles = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PanelCargarDatos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_de_Reportes = new javax.swing.JTable();
        TxtNombreReporte = new javax.swing.JTextField();
        TxtApellidoReporte = new javax.swing.JTextField();
        TxtCorreoReporte = new javax.swing.JTextField();
        TxtUsuarioReporte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Panel_Exit_Reportes = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        ComboBox_Perfil_Usuario = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondodegradado_1.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondodegradado_1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_Reportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Reportes");
        Panel_Reportes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setText("Nombre del documento");
        Panel_Reportes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        Panel_Reporte_Usuarios.setBackground(new java.awt.Color(91, 155, 213));
        Panel_Reporte_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Reporte_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Reporte_UsuariosMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Generar reporte FastChat");

        javax.swing.GroupLayout Panel_Reporte_UsuariosLayout = new javax.swing.GroupLayout(Panel_Reporte_Usuarios);
        Panel_Reporte_Usuarios.setLayout(Panel_Reporte_UsuariosLayout);
        Panel_Reporte_UsuariosLayout.setHorizontalGroup(
            Panel_Reporte_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Reporte_UsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Reporte_UsuariosLayout.setVerticalGroup(
            Panel_Reporte_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Reporte_UsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        Panel_Reportes.add(Panel_Reporte_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 690, 183, -1));
        Panel_Reportes.add(Txt_Nombre_Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 254, 27));

        Panel_Reporte_Perfiles.setBackground(new java.awt.Color(91, 155, 213));
        Panel_Reporte_Perfiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Reporte_Perfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_Reporte_PerfilesMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Generar reporte usuarios");

        javax.swing.GroupLayout Panel_Reporte_PerfilesLayout = new javax.swing.GroupLayout(Panel_Reporte_Perfiles);
        Panel_Reporte_Perfiles.setLayout(Panel_Reporte_PerfilesLayout);
        Panel_Reporte_PerfilesLayout.setHorizontalGroup(
            Panel_Reporte_PerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Reporte_PerfilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Reporte_PerfilesLayout.setVerticalGroup(
            Panel_Reporte_PerfilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Reporte_PerfilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Reportes.add(Panel_Reporte_Perfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, -1, -1));

        PanelCargarDatos.setBackground(new java.awt.Color(91, 155, 213));
        PanelCargarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelCargarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelCargarDatosMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cargar datos ");

        javax.swing.GroupLayout PanelCargarDatosLayout = new javax.swing.GroupLayout(PanelCargarDatos);
        PanelCargarDatos.setLayout(PanelCargarDatosLayout);
        PanelCargarDatosLayout.setHorizontalGroup(
            PanelCargarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCargarDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        PanelCargarDatosLayout.setVerticalGroup(
            PanelCargarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCargarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Reportes.add(PanelCargarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        Tabla_de_Reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Correo", "Usuario", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_de_Reportes);

        Panel_Reportes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 403, 690, 250));
        Panel_Reportes.add(TxtNombreReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 120, 28));
        Panel_Reportes.add(TxtApellidoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 120, 28));
        Panel_Reportes.add(TxtCorreoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 150, 28));
        Panel_Reportes.add(TxtUsuarioReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 150, 28));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setText("Nombre");
        Panel_Reportes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel7.setText("Apellidos");
        Panel_Reportes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel8.setText("Correo");
        Panel_Reportes.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel9.setText("Perfil de usuario");
        Panel_Reportes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel10.setText("Usuario");
        Panel_Reportes.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 55, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Atrás");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panel_Reportes.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 720, -1, -1));

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Panel_Exit_ReportesLayout = new javax.swing.GroupLayout(Panel_Exit_Reportes);
        Panel_Exit_Reportes.setLayout(Panel_Exit_ReportesLayout);
        Panel_Exit_ReportesLayout.setHorizontalGroup(
            Panel_Exit_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Exit_ReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Exit_ReportesLayout.setVerticalGroup(
            Panel_Exit_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Exit_ReportesLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel13))
        );

        Panel_Reportes.add(Panel_Exit_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 30));

        ComboBox_Perfil_Usuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        ComboBox_Perfil_Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "1- Administrador", "2- Usuario estándar" }));
        ComboBox_Perfil_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Reportes.add(ComboBox_Perfil_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 160, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondodegradado_1.png"))); // NOI18N
        Panel_Reportes.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanelCargarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCargarDatosMouseClicked
                         
            Usuarios U = new Usuarios();
            
            U.setNombre(TxtNombreReporte.getText());
            U.setApellido(TxtApellidoReporte.getText());
            U.setCorreo(TxtCorreoReporte.getText());
            U.setUsuario(TxtUsuarioReporte.getText());
            U.setRol(ComboBox_Perfil_Usuario.getSelectedItem().toString());
 
            ArrayUsuarios.add(U);
            
            Tabla.addRow(new Object[]{
                U.getNombre(),
                U.getApellido(),
                U.getCorreo(),
                U.getUsuario(), 
                U.getRol(),
                
            });
    }//GEN-LAST:event_PanelCargarDatosMouseClicked

    private void Panel_Reporte_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Reporte_UsuariosMouseClicked
               
        Diseño_De_Reportes Reporte_FastChat = new Diseño_De_Reportes(Txt_Nombre_Documento.getText(), new Date().toString(), "C:\\Users\\Miche\\Documents\\NetBeansProjects\\FastChat\\Sistema de Mensajería - FastChat\\Sistema de Mensajería - Prueba (1)\\Cambios\\Sistema de Mensajería - Prueba\\src\\Imágenes\\Logo.png");
        Reporte_FastChat.GenerarReporte1();
              
    }//GEN-LAST:event_Panel_Reporte_UsuariosMouseClicked

    private void Panel_Reporte_PerfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Reporte_PerfilesMouseClicked
      
        Diseño_De_Reportes Reporte_Usuarios = new Diseño_De_Reportes(Txt_Nombre_Documento.getText(), new Date().toString(), "C:\\Users\\Miche\\Desktop\\Universidad\\2021\\Programación 1\\Proyecto\\Primer avance del proyecto\\Grupo.png", ArrayUsuarios);
        Reporte_Usuarios.GenerarReporte2();
        
    }//GEN-LAST:event_Panel_Reporte_PerfilesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Contactos C = new Contactos();
        C.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered

        Panel_Exit_Reportes.setBackground(Color.red);
        
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel13MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Perfil_Usuario;
    private javax.swing.JPanel PanelCargarDatos;
    private javax.swing.JPanel Panel_Exit_Reportes;
    private javax.swing.JPanel Panel_Reporte_Perfiles;
    private javax.swing.JPanel Panel_Reporte_Usuarios;
    private javax.swing.JPanel Panel_Reportes;
    private javax.swing.JTable Tabla_de_Reportes;
    private javax.swing.JTextField TxtApellidoReporte;
    private javax.swing.JTextField TxtCorreoReporte;
    private javax.swing.JTextField TxtNombreReporte;
    private javax.swing.JTextField TxtUsuarioReporte;
    private javax.swing.JTextField Txt_Nombre_Documento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
